dbt-proyectoMineria:
  outputs:
    dev:
      dataset: tablas_dep
      job_execution_timeout_seconds: 1200
      job_retries: 1
      keyfile: key.json
      location: US
      method: service-account
      priority: interactive
      project: thinking-pillar-402721
      threads: 1
      type: bigquery
  target: dev

another-profile:
  outputs:
    dev:
    prod:
  target: dev