dbt-proyectoMineria:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: thinking-pillar-402721
      dataset: tablas_dep #cree este conjuto de datos en bigquery para que se pongas lo resultados ahi
      keyfile: key.json
      location: US
      priority: interactive
      job_execution_timeout_seconds: 1200
      job_retries: 1
      threads: 1
  target: dev
